# Generated by Django 4.1.3 on 2022-11-19 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employer', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('actiontaken', models.BooleanField(default=False)),
                ('response1', models.CharField(blank=True, max_length=100, null=True)),
                ('response2', models.CharField(blank=True, max_length=100, null=True)),
                ('myfollowup1', models.CharField(blank=True, max_length=100, null=True)),
                ('myfollowup2', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
